version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: vulnerabilitydb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: secretpassword
    ports:
      - "3333:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8585:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql

volumes:
  mysql-data:

